<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_PaidListings_Model_Base_PlanCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'plan_name',
        'description' => 'plan_description',
        'type' => 'plan_type',
        'price' => 'plan_price',
        'features' => 'plan_features',
        'active' => 'plan_active',
        'featured' => 'plan_featured',
        'weight' => 'plan_weight',
        'currency' => 'plan_currency',
        'entityBundleName' => 'plan_entity_bundle_name',
        'onetime' => 'plan_onetime',
        'recurring' => 'plan_recurring',
        'id' => 'plan_id',
        'created' => 'plan_created',
        'updated' => 'plan_updated',
    );
}