<?php

return array(
	'title' => 'Email notifications',
	'content' => '
	
	<div class="w2dc-docs w2dc-docs-side">
		<h2 id="emails_tab">Email notifications</h2>
		
		This settings tab places on "<em>Directory Admin -> Directory settings</em>" page at the <em>"Email notifications"</em> settings tab.
		
		<i class="fa fa-exclamation-triangle"></i> If you have any problems with email sending/receiving - look at the <a href="[base_url]/documentation/troubleshooting/">troubleshooting section</a>.
		
		<strong>This email will be used for notifications to admin and in "From" field. Required to send emails.</strong> - enter admin email address.
		
		<strong>Days before pre-expiration notification will be sent</strong> - one-time email with pre-expiration notification text will be sent to the email box of listing owner.
		
		<strong>Pre-expiration notification</strong> - tags allowed: [listing] - listing name, [days] - number of days from previous setting, [link] - the link on the listing.
		
		<strong>Expiration notification</strong> - tags allowed: [listing] - listing name and [link] - the link on the listing.
		
		<strong>Registration of new user notification</strong> (this is <a href="[base_url]/documentation/frontend/">frontend submission addon</a> setting) - tags allowed: [author] - listing author name, [listing] - listing name, [login] - user login, [password] - user password, automatically generated by the system.
		
		<strong>Notification to admin about new listing creation</strong> (this is <a href="[base_url]/documentation/frontend/">frontend submission addon</a> setting) - tags allowed: [user] - listing author name, [listing] - listing name, [link] - the link on the listing.
		
		<strong>Notification to admin about listing modification and pending status</strong> (this is <a href="[base_url]/documentation/frontend/">frontend submission addon</a> setting) - tags allowed: [user] - listing author name, [listing] - listing name, [link] - the link on the listing.
		
		<strong>Notification to author about successful listing approval</strong> (this is <a href="[base_url]/documentation/frontend/">frontend submission addon</a> setting) - tags allowed: [author] - listing author name, [listing] - listing name, [link] - the link on the listing.
		
		<strong>Notification of claim to current listing owner</strong> (this is <a href="[base_url]/documentation/frontend/">frontend submission addon</a> setting) - tags allowed: [author] - the name of current author of the listing, [listing] - listing name, [claimer] - claimer user name, [link] - the link to approve or reject the claim, [message] - message from claimer.
		
		<strong>Notification of successful approval of claim</strong> (this is <a href="[base_url]/documentation/frontend/">frontend submission addon</a> setting) - tags allowed: [listing] - listing name, [claimer] - claimer user name, [link] - the link on the listing.
		
		<strong>Notification of claim decline</strong> (this is <a href="[base_url]/documentation/frontend/">frontend submission addon</a> setting) - tags allowed: [listing] - listing name, [claimer] - claimer user name.
		
		<strong>Notification of new invoice</strong> (this is <a href="[base_url]/documentation/payments/">payments addon</a> setting) - tags allowed: [invoice] - invoice title, [id] - invoice ID, [billing] - billing information, [item] - item name, [price] - item price, [link] - the link on the invoice.
		
		<strong>Notification of paid invoice</strong> (this is <a href="[base_url]/documentation/payments/">payments addon</a> setting) - tags allowed: [author] - invoice author name, [invoice] - invoice title, [price] - item price.
		
		<img src="[base_url]/wp-content/uploads/email_notifications.png" class="alignnone size-full" />
	</div>
	
'
);

?>