<?php

return array(
	'title' => 'Listings logos and images',
	'content' => '
		
	<div class="w2dc-docs w2dc-docs-side">
		<h2 id="listings_logos">Listings logos and images</h2>
		
		Following settings are placed on Listings settings tab of the <em>"Directory Admin -> Directory settings"</em> page at the <em>"Listings settings"</em> tab.
		
		<img src="[base_url]/wp-content/uploads/listings_logos_settings.png" class="alignnone size-full" />
		
		<strong>Images required</strong> - when enabled, it is required to upload images to a listing suring submission.
		
		<strong>Enable lightbox on images gallery</strong> - switch on/off lightbox effect for images gallery on single listing pages.
		
		<strong>Enable automatic rotating slideshow on images gallery</strong> - switch on/off auto slider for images gallery on single listing pages.
		
		<strong>The delay in rotation (in ms)</strong> - the delay between rotation of slides (in milliseconds).
		
		<strong>Exclude logo image from images gallery on single listing page</strong> - logo image will be visible only on index and excerpt pages, it will be excluded from single listing page.
		
		<strong>Enable default logo image</strong> - when logo image file was not uploaded the directory will show default image.
		
		<strong>Default logo image</strong> - this image will appear when listing owner did not upload own logo.
		
		<strong>Enable 100% width of images gallery</strong> - make images galley full width of single listing page. When disabled - next setting will be used.
		
		<strong>Images gallery width (in pixels)</strong> - this option works when previous setting was switched off. Images gallery on listing page places at the left side within provided width, right side contains text information.
		
		<strong>Images gallery height (in pixels)</strong> - set to 0 to fit full width.
		
		<strong>Do crop images gallery</strong> - this setting fits images for their proportions you preferred on your site:
		<ul>
			<li><em>"Cut off image to fit width and height of main slide"</em> for popular rectangular images (in this case images may be scaled and cut off).</li>
			<li><em>"Full image inside main slide"</em> for tall and thin images (so images will be scaled to be fully placed inside main slide).</li>
		</ul>
		
		<div style="float: left; margin-right: 50px">
			<img src="[base_url]/wp-content/uploads/docrop_setting_logo_cut.png" width="420" class="alignnone size-full" />
		</div>
		<div style="float: left;">
			<img src="[base_url]/wp-content/uploads/docrop_setting_logo_full.png" width="420" class="alignnone size-full" />
		</div>
		<div style="clear: both;"></div>
		
		<hr />
		
		<h4 id="listings_logos_on_excerpt">Logo images on excerpt pages</h4>
		
		Following settings are placed on Listings settings tab of the <em>"Directory Admin -> Directory settings"</em> page at the <em>"Pages & Views"</em> settings tab. They control images format viewing on excerpt pages in List and Grid views.
		More information about excerpt views settings you can see by the <a href="[base_url]/documentation/settings/pages-views/">link</a>.
		
		<img src="[base_url]/wp-content/uploads/excerpt_logos_settings.png" class="alignnone size-full" />
		
		<strong>Logo image mode</strong> - this setting fits images for their proportions you preferred on your site. The same functionality does <em>"Do crop images gallery"</em> setting at the <em>"Listings logos and images"</em> setting above.

		<strong>Number of columns for listings Grid View</strong> - from 2, 3 or 4 columns for this type of view.
		
		<strong>Aspect ratio of logo in Grid View</strong> - 1:1 (square), 4:3, 16:9 or 2:1
		
		<strong>Wrap logo image by text content in List View</strong> - with enabled option logo image will be wrapped by text - it gives more space for long texts on excerpt pages. Disabled option will give some kind of separate columns: left side will take logo image, right side - text content.
		
		<strong>Listing thumbnail logo width (in pixels) in List View</strong> - controls the width of logo image in List view.
		
		<hr />
		
		<h4 id="listings_images_sizes">Explanation of images sizes</h4>
		
		By default Web 2.0 Directory plugin uses images generated by WordPress in their sizes according to <em>WordPress Media settings</em>. When you upload any image to the site - it makes different copies of an image according to these settings and store all them in <em>"wp-content/uploads/"</em> folder on the host.
		
		<img src="[base_url]/wp-content/uploads/wordpress_media_settings.png" class="alignnone size-full" />
		
		The plugin uses <strong>wp_get_attachment_image_src($attachment_id, $size)</strong> function to get the most relevant image for a listing logo and images in images gallery on single listing page.
		The second parameter $size has some values:
		<ul>
			<li>\'full\' - means to get the biggest uploaded image, is used for images gallery on single listing page</li>
			<li>\'listing-thumbnail\' - special size defined by directory for listings logos on excerpt pages (800x600 pixels), it is generated automatically while uploading on the host</li>
			<li>map marker InfoWindow uses image size according to the <em>"Map InfoWindow logo width"</em> <a href="[base_url]/documentation/maps/markers-icons/">setting</a></li>
		</ul>
		
		<i class="fa fa-exclamation-triangle"></i> If any problems with directory images or you are using some unique image sizes, try this kind of plugins, they can help you <a href="https://wordpress.org/plugins/regenerate-thumbnails/" target="_blank" rel="noopener noreferrer">Regenerate Thumbnails</a>.
	</div>
	
'
);

?>