<?php

return array(
	'title' => 'Listings settings',
	'content' => '
	
	<div class="w2dc-docs w2dc-docs-side">
		<h2 id="listings_tab">Listings settings tab</h2>
		
		<img src="[base_url]/wp-content/uploads/listings_settings.png" class="alignnone size-full" />
		
		<strong>Show listings on home</strong> - this option controls whether to show listings on index page.
		
		<strong>Number of listings on home page</strong> - default is 10 listings per page.
		
		<strong>Number of listings on excerpt pages (categories, locations, tags, search results)</strong>
		
		<strong>Enable contact form on listing page</strong> - whether to show contact listing owner form in a separate tab on single listing page. Contact Form 7 or standard form will be displayed on each listing page.
		
		<strong>Contact Form 7 shortcode</strong> - the plugin was adapted to work with <a href="[base_url]/documentation/contact-forms/">Contact Form 7 plugin</a>. Insert shortcode generated by CF 7 plugin in this field and CF 7 form will be displayed instead of standard contact form. This will work only when CF 7 plugin enabled, otherwise standard contact form will be displayed.
		
		<strong>Show contact form only for logged in users</strong> - only logged in users will see contact form on single listing page (Contact Form 7 or standard form).
		
		<strong>Allow custom contact emails</strong> - users can fill in custom contact email, otherwise <a href="[base_url]/documentation/contact-forms/">contact messages</a> will be sent directly to listing authors email address from his profile.
		<img src="[base_url]/wp-content/uploads/custom_email_metabox.png" class="alignnone size-full" />
		
		<strong>Enable report form</strong> - report admin about a listing using report form.
		
		<strong>Enable bookmarks list</strong> - this option enables/disables "<em>My bookmarks"</em> functionality: when enabled - at the frontend on single listings pages it shows "<em>Add/Remove Bookmark</em>" button. When user clicks to add in bookmarks - the system saves current listing in his cookie, user may click "<em>My bookmarks</em>" and display all his saved listings.
		
		<strong>Show print listing button</strong> - show/hide print listing button on single listing page.
		
		<strong>Show listing in PDF button</strong> - show/hide "<em>Save listing in PDF"</em> button on single listing page. Please note, that this feature uses free 3rd party service <em>pdfmyurl.com</em>. The speed and quality of this service depends on your own server and site accessibility.
		
		<strong>PDF page orientation</strong> - select portrait or landscape page orientation when generating PDF.
		
		<strong>Allow regular users to change listings expiration dates</strong> - with this enabled setting listings owners can manually change expiration dates of their listings, after that date their listings become expired. The change of expiration dates available only for listings with limited active period, not for eternally active listings. Administrators can control expiration dates even if this option is disabled.
		
		<strong>Hide comments (reviews) number on index and excerpt pages</strong> - the number of comments or reviews will be hidden from index and excerpt pages and visible only on listing pages on special tab.
		
		<strong>Hide listing title</strong> - this hides title on a single listing page. It is used when you place special shortcode to display listing title or header in another place of page, like <strong>&#091;webdirectory-listing-header&#093;</strong> or <strong>&#091;webdirectory-page-header&#093;</strong> or <strong>&#091;webdirectory-page-title&#093;</strong>.
		<i class="fa fa-star"></i> Detailed explanation of all shortcodes you can find <a href="[base_url]/documentation/shortcodes/">here</a>.
		
		<strong>Hide listings views counter</strong> - whether to show total clicks on the listing.
		
		<strong>Hide listings creation date</strong> - listings creation date will be hidden at the frontend.
		
		<strong>Hide author information</strong> - author name and possible link to author website will be hidden on single listing pages.
		
		<strong>Listings comments (reviews) mode</strong> - with enabled option "As configured in WP settings" comments visibility depends on WordPress discussion settings - it depends on individual listing setting "Allow comments" on each listing edit screen. <a href="[base_url]/documentation/ratings-reviews-comments/">Ratings and comments section</a>.
		
		<strong>Listing tabs order</strong> - sort tabs on single listing page.
		
		<strong>Enable statistics functionality</strong> - statistics charts visible on frontend users dashboard. At the backend only total number of clicks visible.
		
		<hr />
		
		<h4 id="breadcrumbs_settings">Breadcrumbs settings</h4>
		
		<img src="[base_url]/wp-content/uploads/breadcrumbs_settings.png" class="alignnone size-full" />
		
		<strong>Enable breadcrumbs</strong> - show/hide breadcrumbs links on single listings pages.
		
		<strong>Hide home link in breadcrumbs</strong> - "Home" link will be hidden.
		
		<strong>Breadcrumbs mode on single listing page</strong> - examples of breadcrumbs:
		<ul>
		 	<li><strong>%listing title%</strong> - <em>Home » Super Shopping in LA</em></li>
		 	<li><strong>%category% » %listing title%</strong> - <em>Home » Business Services » Advertising, Marketing &amp; PR » Super Shopping in LA</em></li>
		 	<li><strong>%location% » %listing title%</strong> - <em>Home » United States » California » Los Angeles » Super Shopping in LA</em></li>
		</ul>
		
		<hr />
		
		<h4 id="logos_settings">Listings logos & images</h4>
		
		Listings logos and images settings explained by the <a href="[base_url]/documentation/settings/listings-logos-images/">link</a>.
		
		<hr />
		
		<h4 id="description_excerpt">Description & Excerpt settings</h4>
		
		<img src="[base_url]/wp-content/uploads/listings_description_excerpt_settings.png" class="alignnone size-full" />
		
		<strong>Enable description field</strong> - main description text editor can be hidden from listing.
		
		<strong>Enable summary field</strong> - summary/excerpt field can be hidden from listing.
		
		<strong>Excerpt max length</strong> - insert the number of words you want to show in the listings excerpts.
		
		<strong>Use cropped content as excerpt</strong> - when excerpt field wasn\'t filled in by user - cropped description content will be used.
		
		<strong>Strip HTML from excerpt</strong> - check the box if you want to strip HTML from the excerpt content.
		
	</div>
	
'
);

?>